#!/bin/sh
set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-remove" ]; then
    update-alternatives --install \
        /usr/share/sddm/themes/ubuntu-theme \
        sddm-ubuntu-theme \
        /usr/share/sddm/themes/ubuntu-budgie-login 20
fi

if [ "$1" = "configure" ]; then
    # Generate initial cache
    /usr/share/sddm/themes/ubuntu-budgie-login/scripts/update-sddm-backgrounds-cache || true
fi

# Tag to allow some debhelper commands to inject relevant code
#DEBHELPER#

