#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then

    # Check if the cache file exists and remove it
    if [ -f "/usr/share/sddm/themes/ubuntu-budgie-login/cache/user-backgrounds.json" ]; then
        rm "/usr/share/sddm/themes/ubuntu-budgie-login/cache/user-backgrounds.json"
    fi

    update-alternatives --remove \
        sddm-ubuntu-theme \
        /usr/share/sddm/themes/ubuntu-budgie-login
fi

# Tag to allow some debhelper commands to inject relevant code
#DEBHELPER#

