#! /bin/sh

set -e

case "$1" in
  configure|upgrade)
    if [ -x /usr/lib/lightdm/lightdm-set-defaults ] ; then
      /usr/lib/lightdm/lightdm-set-defaults --keep-old --session=budgie-remix || true
      /usr/lib/lightdm/lightdm-set-defaults --keep-old --greeter=lightdm-gtk-greeter || true
    fi
    ;;
esac

if [ "$1" = "configure" ] ; then
  update-alternatives --install /etc/lightdm/lightdm-gtk-greeter.conf \
    lightdm-gtk-greeter-config-derivative \
    /etc/xdg/xdg-budgie-remix/lightdm/lightdm-gtk-greeter.conf 30
fi

#DEBHELPER#

